---
# file: roles/common/tasks/main.yml

- name: upgrade all packages
  yum: name=* state=latest

- name: Install the common packages
  yum: name={{ item }} state=latest
  with_items:
    - wget
    - git

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config regexp=^[#]?PermitRootLogin line='PermitRootLogin no'
  notify:
    - restart sshd

- name: Disallow SSH password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp=^PasswordAuthentication line='PasswordAuthentication no'
  notify:
    - restart sshd

- name: Disallow SSH GSS API authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp=^GSSAPIAuthentication line='GSSAPIAuthentication no'
  notify:
    - restart sshd

- name: Add ssh users
  user: name={{ item.name }} groups={{ item.groups }}
  with_items: users

- name: Add ssh user keys
  authorized_key: user={{ item.0.name }} key="{{ lookup('file', item.1) }}"
  with_subelements:
     - users
     - authorized

- name: Add user admin to sudoers
  lineinfile: "dest=/etc/sudoers regexp='^%wheel' line='admin ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"